# <font color='blue'>Projeto de Estratégias de Limpeza e Pré-Processamento de dados com linguagem python</font>
## <font color='blue'>Análise de Dados de Telecomunicações</font>
## <font color='blue'>Pré-Processamento de Dados</font>

### <font color='blue'>Importando as bibliotecas</font>

In [5]:
# Biblioteca de calculos matemáticos
import math 
# Biblioteca para manipular o Sistema Operacional
import sys, os 
# Biblioteca para manipular dados
import numpy as np 
import pandas as pd

### <font color='blue'>Carregando os Dados</font>

In [6]:
# Criando uma lista para identificar valores ausentes
lista_labels_valores_ausentes= ["n/a", "na", "undefined"]
# Carregando os dados 
df=pd.read_csv("dataset.csv", na_values=lista_labels_valores_ausentes)
# Verificando o numero de linhas e colunas
df.shape
# Verificando uma amostra do nosso Dataframe
df.head(10)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0
5,1.311448e+19,4/12/2019 21:37,439.0,4/25/2019 8:08,553.0,1074638.0,2.082014e+14,3.366819e+10,3.529841e+13,T89132C,...,21332918.0,2611113.0,7345361.0,6536448.0,710293538.0,13167974.0,654978277.0,4436057.0,30307754.0,754452212.0
6,1.311448e+19,4/13/2019 8:41,612.0,4/25/2019 8:16,168.0,1035261.0,2.082014e+14,3.366537e+10,8.676270e+13,9.16456701058919E+015,...,7234465.0,1886295.0,13231006.0,17981760.0,44796223.0,14084934.0,803653557.0,10649768.0,47925246.0,70562047.0
7,1.304243e+19,4/14/2019 2:11,592.0,4/25/2019 2:26,512.0,951292.0,2.082010e+14,3.376349e+10,8.654640e+13,CELL_208_20_520025_1,...,12189786.0,19735183.0,6858496.0,12075206.0,748906189.0,16149622.0,537601820.0,7714657.0,58813016.0,775350343.0
8,1.311448e+19,4/14/2019 12:48,121.0,4/25/2019 10:22,960.0,941634.0,2.082014e+14,3.369874e+10,3.556241e+13,T42084A,...,18436641.0,10860867.0,10587264.0,8467177.0,821671285.0,6548349.0,172920486.0,14749031.0,42363146.0,861612261.0
9,1.304243e+19,4/15/2019 0:32,0.0,4/25/2019 0:40,284.0,864482.0,2.082003e+14,3.365922e+10,3.557311e+13,L20434C,...,16338345.0,6573194.0,12211149.0,974201.0,811355188.0,1591237.0,64856042.0,12815208.0,22417975.0,850570347.0

In [7]:
# Verificando numeros de linhas e colunas
df.shape

(150001, 55)

In [8]:
# Visualizando as ultimas linhas do meu dataframe
df.tail()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [9]:
# Carregando o dicionário de dados
dicionario=pd.read_excel("Dicionario.xlsx")
# Verificando uma amostra do nosso dicionario de dados
dicionario.head()

      Fields                                        Description
0  bearer id                             xDr session identifier
1  Dur. (ms)                  Total Duration of the xDR (in ms)
2      Start      Start time of the xDR (first frame timestamp)
3   Start ms  Milliseconds offset of start time for the xDR ...
4        End         End time of the xDR (last frame timestamp)

In [10]:
# Vendo os tipos das variaveis 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      140442 non-null  object
 30  Handset Type                              140442 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

## <font color='blue'>Análise Exploratória</font>

In [11]:
# Descrevendo minhas variaveis numericas 
df.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,...,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,...,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,...,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,...,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,...,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

Existem 150.001 linhas e 55 colunas no dataframe. No entanto, temos 56 colunas com seus nomes e descrições no dicionário. Isso significa que há uma coluna descrita, mas não incluída no dataframe. 

Vamos identificar qual é a coluna faltante.Comparando as colunas do meu DataFrame com as colunas do meu Dicionario de Dados

In [12]:
# Concatenando meus 2 Dataframes 
df_compara_colunas = pd.concat([pd.Series(df.columns.tolist()), 
                                dicionario['Fields']],
                               axis = 1)
# Renomeando as colunas
df_compara_colunas.rename(columns = {0: 'Coluna no Dataset', 'Fields': 'Coluna no Dicionario'}, 
                          inplace = True)
# Visualizando meu Dataframe 
display(df_compara_colunas)

,Coluna no Dataset,Coluna no Dicionario
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start ms,Start
3,End,Start ms
4,End ms,End
5,Dur. (ms),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur. (ms).1,Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

`Dur. (Ms)` é ignorado no dataset como visto no índice 1 em **df_compara_colunas**. É aqui que a ordem das colunas começou a mudar. 

Mas o mesmo nome de coluna `Dur. (Ms)` aparece no dataset no índice 5, enquanto o arquivo de dicionário nos diz que é `Dur. (S)` no índice 6. Como as medidas de ambas as colunas diferem conforme mostrado em seus nomes, nós precisamos verificar qual está certo. Para investigar isso, usaremos a coluna `Dur. (Ms) .1` que se encontra nos índices 28 e 29 no dataset e no arquivo de dicionário, respectivamente.

In [13]:
# Selecionando as duas colunas que iremos analisar 
df[['Dur. (ms)', 'Dur. (ms).1']]

        Dur. (ms)   Dur. (ms).1
0       1823652.0  1.823653e+09
1       1365104.0  1.365104e+09
2       1361762.0  1.361763e+09
3       1321509.0  1.321510e+09
4       1089009.0  1.089009e+09
...           ...           ...
149996    81230.0  8.123076e+07
149997    97970.0  9.797070e+07
149998    98249.0  9.824953e+07
149999    97910.0  9.791063e+07
150000        NaN           NaN

[150001 rows x 2 columns]

Parece que a coluna `Dur. (Ms)` é medida em segundos. Portanto, vamos renomeá-la apropriadamente.

Vamos também renomear algumas das colunas para que fiquem claras como sua descrição e sigam o estilo de nomenclatura de outras colunas.

In [14]:
# Renomeando colunas
df.rename(columns = {'Dur. (ms)': 'Dur (s)', 
                          'Dur. (ms).1': 'Dur (ms)', 
                          'Start ms': 'Start Offset (ms)', 
                          'End ms': 'End Offset (ms)'}, 
               inplace = True)
# Avaliando 
df.head(10)

,Bearer Id,Start,Start Offset (ms),End,End Offset (ms),Dur (s),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0
5,1.311448e+19,4/12/2019 21:37,439.0,4/25/2019 8:08,553.0,1074638.0,2.082014e+14,3.366819e+10,3.529841e+13,T89132C,...,21332918.0,2611113.0,7345361.0,6536448.0,710293538.0,13167974.0,654978277.0,4436057.0,30307754.0,754452212.0
6,1.311448e+19,4/13/2019 8:41,612.0,4/25/2019 8:16,168.0,1035261.0,2.082014e+14,3.366537e+10,8.676270e+13,9.16456701058919E+015,...,7234465.0,1886295.0,13231006.0,17981760.0,44796223.0,14084934.0,803653557.0,10649768.0,47925246.0,70562047.0
7,1.304243e+19,4/14/2019 2:11,592.0,4/25/2019 2:26,512.0,951292.0,2.082010e+14,3.376349e+10,8.654640e+13,CELL_208_20_520025_1,...,12189786.0,19735183.0,6858496.0,12075206.0,748906189.0,16149622.0,537601820.0,7714657.0,58813016.0,775350343.0
8,1.311448e+19,4/14/2019 12:48,121.0,4/25/2019 10:22,960.0,941634.0,2.082014e+14,3.369874e+10,3.556241e+13,T42084A,...,18436641.0,10860867.0,10587264.0,8467177.0,821671285.0,6548349.0,172920486.0,14749031.0,42363146.0,861612261.0
9,1.304243e+19,4/15/2019 0:32,0.0,4/25/2019 0:40,284.0,864482.0,2.082003e+14,3.365922e+10,3.557311e+13,L20434C,...,16338345.0,6573194.0,12211149.0,974201.0,811355188.0,1591237.0,64856042.0,12815208.0,22417975.0,850570347.0

## <font color='blue'>Limpeza dos Dados</font>

## Estratégia de Limpeza 1 - Tratamento de Valores Ausentes

    Tecnicas a serem aplicadas
- 1- Identificando  Valores Ausentes
- 2- Drop de Colunas com mais de 30% de valores ausentes
- 3- Imputação com Preenchimento Reverso (BFILL)
- 4- Imputação com Preenchimento Progressivo (FFILL)
- 5- Imputação de Variáveis Categóricas
- 6- Drop de Linhas com um % baixo

In [15]:
# Criando uma fuction para identificar o percentual de valores ausentes 
# Calcula o percentual de valores ausentes em todo o meu DataFrame
def func_calc_percentual_valores_ausentes(df):
    totalCells = np.product(df.shape)
    missingCount = df.isnull().sum()
    totalMissing = missingCount.sum()
    print("O dataset tem", round(((totalMissing/totalCells) * 100), 2), "%", "de valores ausentes.")

In [16]:
func_calc_percentual_valores_ausentes(df)

O dataset tem 12.72 % de valores ausentes.

Esta função irá indentificar os valoes nulos (NaN) , não necessariamente os valores ausentes, visto que, valor ausente é a ausência de INFORMAÇÃO , não de dados.

In [17]:
# Calculando o total de valores ausentes e o percentual por variável e colocando em um Dataset
# Função para calcular valores ausentes por coluna
def func_calc_percentual_valores_ausentes_coluna(df):
    # Total de valores ausentes
    mis_val = df.isnull().sum()
    # Porcentagem de valores ausentes
    mis_val_percent = 100 * mis_val / len(df)
    # Tipo de dado das colunas com valores ausentes
    mis_val_dtype = df.dtypes
    # Cria uma tabela com os resultados
    mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_dtype], axis=1)
    # Renomear as colunas
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Valores Ausentes', 1 : '% de Valores Ausentes', 2: 'Dtype'})
    # Classifica a tabela por porcentagem de valores ausentes de forma decrescente e remove colunas sem valores faltantes
    mis_val_table_ren_columns = mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,0] != 0].sort_values('% de Valores Ausentes', ascending = False).round(2)
    # Print 
    print ("O dataset tem " + str(df.shape[1]) + " colunas.\n"
        "Encontrado: " + str(mis_val_table_ren_columns.shape[0]) + " colunas que têm valores ausentes.")
    if mis_val_table_ren_columns.shape[0] == 0:
        return
    # Retorna o dataframe com informações ausentes
    return mis_val_table_ren_columns

In [18]:
func_calc_percentual_valores_ausentes(df)
df_missing = func_calc_percentual_valores_ausentes_coluna(df)
# Visualizando o Dataframe
df_missing

O dataset tem 12.72 % de valores ausentes.
O dataset tem 55 colunas.
Encontrado: 41 colunas que têm valores ausentes.

,Valores Ausentes,% de Valores Ausentes,Dtype
Nb of sec with 37500B < Vol UL,130254,86.84,float64
Nb of sec with 6250B < Vol UL < 37500B,111843,74.56,float64
Nb of sec with 125000B < Vol DL,97538,65.02,float64
TCP UL Retrans. Vol (Bytes),96649,64.43,float64
Nb of sec with 31250B < Vol DL < 125000B,93586,62.39,float64
Nb of sec with 1250B < Vol UL < 6250B,92894,61.93,float64
Nb of sec with 6250B < Vol DL < 31250B,88317,58.88,float64
TCP DL Retrans. Vol (Bytes),88146,58.76,float64
HTTP UL (Bytes),81810,54.54,float64
HTTP DL (Bytes),81474,54.32,float64
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Manufacturer,9559,6.37,object
Handset Type,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
Start,1,0.00,object
End Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Start Offset (ms),1,0.00,float64
End,1,0.00,object
Avg Bearer TP DL (kbps),1,0.00,float64
Dur (s),1,0.00,float64
Avg Bearer TP UL (kbps),1,0.00,float64
Dur (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Total DL (Bytes),1,0.00,float64

-Iremos utilizar um conceito quando se trata de % de valores ausentes

-Removeremos as colunas que tem mais de 30% de valores ausentes

In [19]:
# Fazendo uma lista das colunas que serão removidas
lista=df_missing[df_missing['% de Valores Ausentes']>=30.0].index.tolist()

In [20]:
# Colunas que serão removidas
colunas_para_remover = [col for col in lista if col not in ['TCP UL Retrans. Vol (Bytes)',
    'TCP DL Retrans. Vol (Bytes)']]
# Visualizando a lista
colunas_para_remover

['Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'HTTP UL (Bytes)',
 'HTTP DL (Bytes)']

Mesmo que as variáveis `TCP DL Retrans. Vol (Bytes)` e `TCP UL Retrans. Vol (Bytes)` tenham muitos valores ausentes, em vez de removê-las, iremos imputá-las, uma vez que elas podem ser necessárias para nossa análise posterior.

In [21]:
# Criando um novo Dataset 
df_limpo=df.drop(colunas_para_remover,axis=1)
# Visualizando o Dataset 
df_limpo

,Bearer Id,Start,Start Offset (ms),End,End Offset (ms),Dur (s),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [22]:
# Avaliacao 
func_calc_percentual_valores_ausentes(df_limpo)
func_calc_percentual_valores_ausentes_coluna(df_limpo)

O dataset tem 3.85 % de valores ausentes.
O dataset tem 47 colunas.
Encontrado: 33 colunas que têm valores ausentes.

,Valores Ausentes,% de Valores Ausentes,Dtype
TCP UL Retrans. Vol (Bytes),96649,64.43,float64
TCP DL Retrans. Vol (Bytes),88146,58.76,float64
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

Uma vez que as porcentagens ausentes de `'TCP UL Retrans. Vol (Bytes)` e `TCP DL Retrans. Vol (Bytes)`são muito altos, iremos imputá-los com o método de preenchimento reverso usando o método Bfill.

 method = 'bfill': Bfill ou backward-fill propaga o primeiro valor não nulo observado para trás até que outro valor não nulo seja encontrado

In [23]:
# Fazendo o preenchimento reverso 
# Imputação de valores ausentes usando backward fill
def fix_missing_bfill(df, col):
    count = df[col].isna().sum()
    df[col] = df[col].fillna(method = 'bfill')
    print(f"{count} valores ausentes na coluna {col} foram substituídos usando o método de preenchimento reverso.")
    return df[col]

In [24]:
# Aplicando o método backward fill
fix_missing_bfill(df_limpo, 'TCP UL Retrans. Vol (Bytes)')
fix_missing_bfill(df_limpo,'TCP DL Retrans. Vol (Bytes)' )

96649 valores ausentes na coluna TCP UL Retrans. Vol (Bytes) foram substituídos usando o método de preenchimento reverso.
88146 valores ausentes na coluna TCP DL Retrans. Vol (Bytes) foram substituídos usando o método de preenchimento reverso.

0         19520.0
1         19520.0
2         19520.0
3         19520.0
4         19520.0
           ...
149996        NaN
149997        NaN
149998        NaN
149999        NaN
150000        NaN
Name: TCP DL Retrans. Vol (Bytes), Length: 150001, dtype: float64

In [25]:
# Avaliacao 
func_calc_percentual_valores_ausentes(df_limpo)
func_calc_percentual_valores_ausentes_coluna(df_limpo)

O dataset tem 1.23 % de valores ausentes.
O dataset tem 47 colunas.
Encontrado: 33 colunas que têm valores ausentes.

,Valores Ausentes,% de Valores Ausentes,Dtype
Avg RTT DL (ms),27829,18.55,float64
Avg RTT UL (ms),27812,18.54,float64
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

Já `Avg RTT DL (ms)` e `Avg RTT UL (ms)` têm as próximas porcentagens mais altas de valores ausentes com cerca de 18,5% cada. Vamos verificar se as variáveis estão enviesadas (não seguem uma distribuição normal).A partir daí vejo se posso substituir as valores ausentes pela media ou mediana

In [26]:
# Calculando a assimetria 
print(" A Avg RTT DL(ms): {}".format(df_limpo['Avg RTT DL (ms)'].skew(skipna = True)))
print(" A Avg RTT UL(ms): {}".format(df_limpo['Avg RTT UL (ms)'].skew(skipna = True)))

 A Avg RTT DL(ms): 62.90782807995961
 A Avg RTT UL(ms): 28.45741458546382

Interpretamos a assimetria assim:

    - Se a assimetria estiver entre -0,5 e 0,5 os dados são bastante simétricos
    - Se a assimetria estiver entre -1 e - 0,5 ou entre 0,5 e 1, os dados estão               moderadamente inclinados
    - Se a assimetria for menor que -1 ou maior que 1, os dados estão altamente enviesados

Vimos que minhas duas variaveis não seguem uma distribuição normal ( Estão bastante enviesados ) então aplicaremos o método de preechimento progressivo  usando o método Ffill.

method = 'ffill': Ffill ou forward-fill propaga o último valor não nulo observado para frente até que outro valor não nulo seja encontrado

In [27]:
# Fazendo o preechimento progressivo
# Imputação de valores ausentes usando forward fill 
def fix_missing_ffill(df, col):
    count = df[col].isna().sum()
    df[col] = df[col].fillna(method = 'ffill')
    print(f"{count} valores ausentes na coluna {col} foram substituídos usando o método de preenchimento progressivo.")
    return df[col]

In [28]:
fix_missing_ffill(df_limpo,'Avg RTT DL (ms)')
fix_missing_ffill(df_limpo,'Avg RTT UL (ms)')

27829 valores ausentes na coluna Avg RTT DL (ms) foram substituídos usando o método de preenchimento progressivo.
27812 valores ausentes na coluna Avg RTT UL (ms) foram substituídos usando o método de preenchimento progressivo.

0         5.0
1         5.0
2         5.0
3         5.0
4         5.0
         ...
149996    0.0
149997    2.0
149998    6.0
149999    5.0
150000    5.0
Name: Avg RTT UL (ms), Length: 150001, dtype: float64

In [29]:
# Avaliacao 
func_calc_percentual_valores_ausentes(df_limpo)
func_calc_percentual_valores_ausentes_coluna(df_limpo)

O dataset tem 0.44 % de valores ausentes.
O dataset tem 47 colunas.
Encontrado: 31 colunas que têm valores ausentes.

,Valores Ausentes,% de Valores Ausentes,Dtype
Handset Type,9559,6.37,object
Handset Manufacturer,9559,6.37,object
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
End,1,0.00,object
Start Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

Visto que `Handset Type` e `Handset Manufacturer` são colunas categóricas, é melhor imputá-los com o valor "unknown" para que não enviesemos os dados.

In [30]:
# Preenche valor NA
def fix_missing_value(df, col, value):
    count = df[col].isna().sum()
    df[col] = df[col].fillna(value)
    if type(value) == 'str':
        print(f"{count} valores ausentes na coluna {col} foram substituídos por '{value}'.")
    else:
        print(f"{count} valores ausentes na coluna {col} foram substituídos por {value}.")
    return df[col]

In [31]:
fix_missing_value(df_limpo,'Handset Type','unknown')
fix_missing_value(df_limpo,"Handset Manufacturer" ,'unknown')

9559 valores ausentes na coluna Handset Type foram substituídos por unknown.
9559 valores ausentes na coluna Handset Manufacturer foram substituídos por unknown.

0         Samsung
1         Samsung
2         Samsung
3         unknown
4         Samsung
           ...
149996      Apple
149997      Apple
149998      Apple
149999     Huawei
150000    unknown
Name: Handset Manufacturer, Length: 150001, dtype: object

In [32]:
# Avaliacao 
func_calc_percentual_valores_ausentes(df_limpo)
func_calc_percentual_valores_ausentes_coluna(df_limpo)

O dataset tem 0.17 % de valores ausentes.
O dataset tem 47 colunas.
Encontrado: 29 colunas que têm valores ausentes.

,Valores Ausentes,% de Valores Ausentes,Dtype
Last Location Name,1153,0.77,object
MSISDN/Number,1066,0.71,float64
Bearer Id,991,0.66,float64
Nb of sec with Vol UL < 1250B,793,0.53,float64
UL TP > 300 Kbps (%),792,0.53,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.53,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.53,float64
UL TP < 10 Kbps (%),792,0.53,float64
Nb of sec with Vol DL < 6250B,755,0.50,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.50,float64
DL TP > 1 Mbps (%),754,0.50,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.50,float64
DL TP < 50 Kbps (%),754,0.50,float64
IMEI,572,0.38,float64
IMSI,570,0.38,float64
TCP UL Retrans. Vol (Bytes),5,0.00,float64
TCP DL Retrans. Vol (Bytes),5,0.00,float64
Start,1,0.00,object
Avg Bearer TP UL (kbps),1,0.00,float64
Avg Bearer TP DL (kbps),1,0.00,float64
Dur (s),1,0.00,float64
End Offset (ms),1,0.00,float64
Activity Duration DL (ms),1,0.00,float64
Activity Duration UL (ms),1,0.00,float64
Dur (ms),1,0.00,float64
End,1,0.00,object
Start Offset (ms),1,0.00,float64
Total UL (Bytes),1,0.00,float64
Total DL (Bytes),1,0.00,float64

Iremos remover os restos das minhas linhas ausentes,visto que o % é extremamente baixo

In [33]:
# Drop de linhas com valores ausentes
def drop_rows_with_missing_values(df):
    old = df.shape[0]
    df.dropna(inplace = True)
    new = df.shape[0]
    count = old - new
    print(f"{count} linhas contendo valores ausentes foram descartadas.")

In [34]:
# Executando a fuction
drop_rows_with_missing_values(df_limpo)

3114 linhas contendo valores ausentes foram descartadas.

In [35]:
# Avaliacao 
func_calc_percentual_valores_ausentes(df_limpo)
func_calc_percentual_valores_ausentes_coluna(df_limpo)
df_limpo.shape

O dataset tem 0.0 % de valores ausentes.
O dataset tem 47 colunas.
Encontrado: 0 colunas que têm valores ausentes.

(146887, 47)

## Estratégia de Limpeza 2 - Conversão de Tipos de Dados

In [36]:
# Verificando como o pandas interpretou meu Dataframe
df_limpo.dtypes

Bearer Id                         float64
Start                              object
Start Offset (ms)                 float64
End                                object
End Offset (ms)                   float64
Dur (s)                           float64
IMSI                              float64
MSISDN/Number                     float64
IMEI                              float64
Last Location Name                 object
Avg RTT DL (ms)                   float64
Avg RTT UL (ms)                   float64
Avg Bearer TP DL (kbps)           float64
Avg Bearer TP UL (kbps)           float64
TCP DL Retrans. Vol (Bytes)       float64
TCP UL Retrans. Vol (Bytes)       float64
DL TP < 50 Kbps (%)               float64
50 Kbps < DL TP < 250 Kbps (%)    float64
250 Kbps < DL TP < 1 Mbps (%)     float64
DL TP > 1 Mbps (%)                float64
UL TP < 10 Kbps (%)               float64
10 Kbps < UL TP < 50 Kbps (%)     float64
50 Kbps < UL TP < 300 Kbps (%)    float64
UL TP > 300 Kbps (%)              float64
Activity Duration DL (ms)         float64
Activity Duration UL (ms)         float64
Dur (ms)                          float64
Handset Manufacturer               object
Handset Type                       object
Nb of sec with Vol DL < 6250B     float64
Nb of sec with Vol UL < 1250B     float64
Social Media DL (Bytes)           float64
Social Media UL (Bytes)           float64
Google DL (Bytes)                 float64
Google UL (Bytes)                 float64
Email DL (Bytes)                  float64
Email UL (Bytes)                  float64
Youtube DL (Bytes)                float64
Youtube UL (Bytes)                float64
Netflix DL (Bytes)                float64
Netflix UL (Bytes)                float64
Gaming DL (Bytes)                 float64
Gaming UL (Bytes)                 float64
Other DL (Bytes)                  float64
Other UL (Bytes)                  float64
Total UL (Bytes)                  float64
Total DL (Bytes)                  float64
dtype: object

In [37]:
# Visualizando uma amostra dos meus dados
df_limpo.head(10)

,Bearer Id,Start,Start Offset (ms),End,End Offset (ms),Dur (s),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0
5,1.311448e+19,4/12/2019 21:37,439.0,4/25/2019 8:08,553.0,1074638.0,2.082014e+14,3.366819e+10,3.529841e+13,T89132C,...,21332918.0,2611113.0,7345361.0,6536448.0,710293538.0,13167974.0,654978277.0,4436057.0,30307754.0,754452212.0
6,1.311448e+19,4/13/2019 8:41,612.0,4/25/2019 8:16,168.0,1035261.0,2.082014e+14,3.366537e+10,8.676270e+13,9.16456701058919E+015,...,7234465.0,1886295.0,13231006.0,17981760.0,44796223.0,14084934.0,803653557.0,10649768.0,47925246.0,70562047.0
7,1.304243e+19,4/14/2019 2:11,592.0,4/25/2019 2:26,512.0,951292.0,2.082010e+14,3.376349e+10,8.654640e+13,CELL_208_20_520025_1,...,12189786.0,19735183.0,6858496.0,12075206.0,748906189.0,16149622.0,537601820.0,7714657.0,58813016.0,775350343.0
8,1.311448e+19,4/14/2019 12:48,121.0,4/25/2019 10:22,960.0,941634.0,2.082014e+14,3.369874e+10,3.556241e+13,T42084A,...,18436641.0,10860867.0,10587264.0,8467177.0,821671285.0,6548349.0,172920486.0,14749031.0,42363146.0,861612261.0
9,1.304243e+19,4/15/2019 0:32,0.0,4/25/2019 0:40,284.0,864482.0,2.082003e+14,3.365922e+10,3.557311e+13,L20434C,...,16338345.0,6573194.0,12211149.0,974201.0,811355188.0,1591237.0,64856042.0,12815208.0,22417975.0,850570347.0

Observando as colunas, podemos perceber que as colunas `Start` e `End` são, na verdade, valores de data e hora, embora sejam rotuladas como objetos pelo pandas. Além dessas duas colunas, todas as outras colunas com tipos de dados de objeto são, na verdade, valores de string. Portanto, vamos converter essas colunas em seus tipos de dados apropriados.

In [38]:
# Criando uma funcao que converte a variável para o tipo de data 
def convert_to_datetime(df, columns):
    for col in columns:
        df[col] = pd.to_datetime(df[col])

In [39]:
# Executando a função
convert_to_datetime(df_limpo, ['Start', 'End'])

In [40]:
# Pegando minhas colunas com o tipo object
string_columns=df_limpo.select_dtypes(include='object').columns.tolist()
# Visualizando
string_columns

['Last Location Name', 'Handset Manufacturer', 'Handset Type']

In [41]:
# Criar uma funcao que converte a variavel para o tipo de string
def convert_to_string(df, columns):
    for col in columns:
        df[col] = df[col].astype("string")

In [42]:
# Executando a funcao
convert_to_string(df_limpo, string_columns)

In [43]:
# Avalia
df_limpo.dtypes

Bearer Id                                float64
Start                             datetime64[ns]
Start Offset (ms)                        float64
End                               datetime64[ns]
End Offset (ms)                          float64
Dur (s)                                  float64
IMSI                                     float64
MSISDN/Number                            float64
IMEI                                     float64
Last Location Name                        string
Avg RTT DL (ms)                          float64
Avg RTT UL (ms)                          float64
Avg Bearer TP DL (kbps)                  float64
Avg Bearer TP UL (kbps)                  float64
TCP DL Retrans. Vol (Bytes)              float64
TCP UL Retrans. Vol (Bytes)              float64
DL TP < 50 Kbps (%)                      float64
50 Kbps < DL TP < 250 Kbps (%)           float64
250 Kbps < DL TP < 1 Mbps (%)            float64
DL TP > 1 Mbps (%)                       float64
UL TP < 10 Kbps (%)                      float64
10 Kbps < UL TP < 50 Kbps (%)            float64
50 Kbps < UL TP < 300 Kbps (%)           float64
UL TP > 300 Kbps (%)                     float64
Activity Duration DL (ms)                float64
Activity Duration UL (ms)                float64
Dur (ms)                                 float64
Handset Manufacturer                      string
Handset Type                              string
Nb of sec with Vol DL < 6250B            float64
Nb of sec with Vol UL < 1250B            float64
Social Media DL (Bytes)                  float64
Social Media UL (Bytes)                  float64
Google DL (Bytes)                        float64
Google UL (Bytes)                        float64
Email DL (Bytes)                         float64
Email UL (Bytes)                         float64
Youtube DL (Bytes)                       float64
Youtube UL (Bytes)                       float64
Netflix DL (Bytes)                       float64
Netflix UL (Bytes)                       float64
Gaming DL (Bytes)                        float64
Gaming UL (Bytes)                        float64
Other DL (Bytes)                         float64
Other UL (Bytes)                         float64
Total UL (Bytes)                         float64
Total DL (Bytes)                         float64
dtype: object

Também sabemos que `Bearer Id`, `IMSI`, `MSISDN / Number`, `IMEI` são números únicos usados para identificação. Portanto, para melhor legibilidade (e facilitar os filtros usados mais frente), vamos alterá-los de float64 para int64.

In [44]:
# Lista de colunas para conversão
int_cols = ['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI']
# Visualizando
int_cols

['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI']

In [45]:
# Criar uma funcao que converte a variavel para o tipo int
def convert_to_int(df, columns):
    for col in columns:
        df[col] = df[col].astype("int64")

In [46]:
# Executando a funcao
convert_to_int(df_limpo, int_cols)

In [47]:
# Avalia
df_limpo.dtypes

Bearer Id                                  int64
Start                             datetime64[ns]
Start Offset (ms)                        float64
End                               datetime64[ns]
End Offset (ms)                          float64
Dur (s)                                  float64
IMSI                                       int64
MSISDN/Number                              int64
IMEI                                       int64
Last Location Name                        string
Avg RTT DL (ms)                          float64
Avg RTT UL (ms)                          float64
Avg Bearer TP DL (kbps)                  float64
Avg Bearer TP UL (kbps)                  float64
TCP DL Retrans. Vol (Bytes)              float64
TCP UL Retrans. Vol (Bytes)              float64
DL TP < 50 Kbps (%)                      float64
50 Kbps < DL TP < 250 Kbps (%)           float64
250 Kbps < DL TP < 1 Mbps (%)            float64
DL TP > 1 Mbps (%)                       float64
UL TP < 10 Kbps (%)                      float64
10 Kbps < UL TP < 50 Kbps (%)            float64
50 Kbps < UL TP < 300 Kbps (%)           float64
UL TP > 300 Kbps (%)                     float64
Activity Duration DL (ms)                float64
Activity Duration UL (ms)                float64
Dur (ms)                                 float64
Handset Manufacturer                      string
Handset Type                              string
Nb of sec with Vol DL < 6250B            float64
Nb of sec with Vol UL < 1250B            float64
Social Media DL (Bytes)                  float64
Social Media UL (Bytes)                  float64
Google DL (Bytes)                        float64
Google UL (Bytes)                        float64
Email DL (Bytes)                         float64
Email UL (Bytes)                         float64
Youtube DL (Bytes)                       float64
Youtube UL (Bytes)                       float64
Netflix DL (Bytes)                       float64
Netflix UL (Bytes)                       float64
Gaming DL (Bytes)                        float64
Gaming UL (Bytes)                        float64
Other DL (Bytes)                         float64
Other UL (Bytes)                         float64
Total UL (Bytes)                         float64
Total DL (Bytes)                         float64
dtype: object

## Estratégia de Limpeza 3 - Tratar registro Duplicado

In [48]:
# Criando minha funcao
def drop_duplicates(df):
    old = df.shape[0]
    df.drop_duplicates(inplace = True)
    new = df.shape[0]
    count = old - new
    if (count == 0):
        print("Nenhuma linha duplicada foi encontrada.")
    else:
        print(f"{count} linhas duplicadas foram encontradas e removidas.")

In [49]:
drop_duplicates(df_limpo)

Nenhuma linha duplicada foi encontrada.

Vimos que não temos registro duplicados

## Estratégia de Limpeza 4 - Engenharia de Atributos

Como vimos na seção de limpeza da coluna, temos duas colunas de duração, uma em segundos e a outra em microssegundos.Vamos manter apenas uma ( `Dur (ms)`)

In [50]:
# Drop de colunas
def drop_columns(df, columns):
    df.drop(columns, axis = 1, inplace = True)
    count = len(columns)
    if count == 1:
        print(f"{count} coluna foi descartada.")
    else:
        print(f"{count} colunas foram descartadas.")

In [51]:
# Executando a função
drop_columns(df_limpo, ['Dur (s)'])

1 coluna foi descartada.

## Estratégia de Limpeza 5 - Tratando Outliers

![title](outliers.png)

Iremos usar esta estratégia para indentificar e tratar os valores outliers

In [52]:
# Criando uma funcao 
class TrataOutlier:

    # Construtor
    def __init__(self, df: pd.DataFrame) -> None:
        self.df = df

    def count_outliers(self, Q1, Q3, IQR, columns):
        cut_off = IQR * 1.5
        temp_df = (self.df[columns] < (Q1 - cut_off)) | (self.df[columns] > (Q3 + cut_off))
        return [len(temp_df[temp_df[col] == True]) for col in temp_df]

    def calc_skew(self, columns=None):
        if columns == None:
            columns = self.df.columns
        return [self.df[col].skew() for col in columns]

    def percentage(self, list):
        return [str(round(((value/150001) * 100), 2)) + '%' for value in list]

    def remove_outliers(self, columns):
        for col in columns:
            Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)
            IQR = Q3 - Q1
            cut_off = IQR * 1.5
            lower, upper = Q1 - cut_off, Q3 + cut_off
            self.df = self.df.drop(self.df[self.df[col] > upper].index)
            self.df = self.df.drop(self.df[self.df[col] < lower].index)

    def replace_outliers_with_fences(self, columns):
        for col in columns:
            Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)
            IQR = Q3 - Q1
            cut_off = IQR * 1.5
            lower, upper = Q1 - cut_off, Q3 + cut_off

            self.df[col] = np.where(self.df[col] > upper, upper, self.df[col])
            self.df[col] = np.where(self.df[col] < lower, lower, self.df[col])

    def getOverview(self, columns) -> None:
        min = self.df[columns].min()
        Q1 = self.df[columns].quantile(0.25)
        median = self.df[columns].quantile(0.5)
        Q3 = self.df[columns].quantile(0.75)
        max = self.df[columns].max()
        IQR = Q3 - Q1
        skew = self.calc_skew(columns)
        outliers = self.count_outliers(Q1, Q3, IQR, columns)
        cut_off = IQR * 1.5
        lower, upper = Q1 - cut_off, Q3 + cut_off

        new_columns = ['Nome de Coluna', 'Min', 'Q1', 'Median', 'Q3', 'Max', 'IQR', 'Lower fence', 'Upper fence', 'Skew', 'Num_Outliers', 'Percent_Outliers' ]
        
        data = zip([column for column in self.df[columns]], min, Q1, median, Q3, max, IQR, lower, upper, skew, outliers, self.percentage(outliers))

        new_df = pd.DataFrame(data = data, columns = new_columns)
        
        new_df.set_index('Nome de Coluna', inplace = True)
        \
        return new_df.sort_values('Num_Outliers', ascending = False).transpose()

In [53]:
# Cria o objeto que trata o outlier
trata_outlier=TrataOutlier(df_limpo)

In [54]:
# Criando uma lista com as variaveis float 
lista_colunas = df_limpo.select_dtypes('float64').columns.tolist()

In [55]:
# Visão geral dos outliers antes
trata_outlier.getOverview(lista_colunas)

Nome de Coluna,DL TP > 1 Mbps (%),10 Kbps < UL TP < 50 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B,UL TP < 10 Kbps (%),TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps),...,Start Offset (ms),Youtube DL (Bytes),Email UL (Bytes),Email DL (Bytes),Google UL (Bytes),Google DL (Bytes),Social Media UL (Bytes),Social Media DL (Bytes),End Offset (ms),Total DL (Bytes)
Min,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,...,0.0,53.0,2.0,14.0,3.0,207.0,0.0,12.0,0.0,7114041.0
Q1,0.0,0.0,0.0,15418.0,22073.0,107.0,87.0,99.0,24895.0,47.0,...,250.0,5833462.0,233439.0,892573.0,1024371.5,2882586.5,16431.0,898089.0,251.0,243073402.5
Median,0.0,0.0,0.0,39726.0,47180.0,217.0,201.0,100.0,391635.0,63.0,...,499.0,11616334.0,466357.0,1793613.0,2054793.0,5766724.0,32908.0,1793409.0,500.0,455963875.0
Q3,0.0,0.0,1.0,697298.5,611803.0,2466.5,2612.5,100.0,3078146.0,1136.0,...,749.0,17440635.5,700297.5,2689818.0,3088071.5,8625551.0,49326.5,2694640.0,750.0,665783068.0
Max,94.0,98.0,76.0,136536461.0,144911293.0,604122.0,604061.0,100.0,4294425570.0,58613.0,...,999.0,23259098.0,936418.0,3586146.0,4121357.0,11462832.0,65870.0,3586064.0,999.0,902969616.0
IQR,0.0,0.0,1.0,681880.5,589730.0,2359.5,2525.5,1.0,3053251.0,1089.0,...,499.0,11607173.5,466858.5,1797245.0,2063700.0,5742964.5,32895.5,1796551.0,499.0,422709665.5
Lower fence,0.0,0.0,-1.5,-1007402.75,-862522.0,-3432.25,-3701.25,97.5,-4554981.5,-1586.5,...,-498.5,-11577298.25,-466848.75,-1803294.5,-2071178.5,-5731860.25,-32912.25,-1796737.5,-497.5,-390991095.75
Upper fence,0.0,0.0,2.5,1720119.25,1496398.0,6005.75,6400.75,101.5,7658022.5,2769.5,...,1497.5,34851395.75,1400585.25,5385685.5,6183621.5,17239997.75,98669.75,5389466.5,1498.5,1299847566.25
Skew,5.345557,10.941071,4.503234,5.821286,7.321154,7.467915,9.009273,-8.958674,16.755094,4.473627,...,0.000823,0.000119,0.007312,-0.002659,0.002242,-0.008414,0.000258,-0.001633,-0.001251,-0.003579
Num_Outliers,36594,31509,29343,26126,25501,24870,24604,21811,21625,21104,...,0,0,0,0,0,0,0,0,0,0
Percent_Outliers,24.4%,21.01%,19.56%,17.42%,17.0%,16.58%,16.4%,14.54%,14.42%,14.07%,...,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%

In [56]:
# Replace dos outliers
trata_outlier.replace_outliers_with_fences(lista_colunas)

In [57]:
# Visão geral dos outliers depois 
trata_outlier.getOverview(lista_colunas)

Nome de Coluna,Start Offset (ms),Nb of sec with Vol DL < 6250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),...,DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Total DL (Bytes)
Min,0.0,1.0,12.0,0.0,207.0,3.0,14.0,2.0,53.0,105.0,...,77.5,0.0,0.0,0.0,97.5,0.0,0.0,0.0,0.0,7114041.0
Q1,250.0,87.0,898089.0,16431.0,2882586.5,1024371.5,892573.0,233439.0,5833462.0,5516549.0,...,91.0,0.0,0.0,0.0,99.0,0.0,0.0,0.0,15418.0,243073402.5
Median,499.0,201.0,1793409.0,32908.0,5766724.0,2054793.0,1793613.0,466357.0,11616334.0,11013447.0,...,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,39726.0,455963875.0
Q3,749.0,2612.5,2694640.0,49326.5,8625551.0,3088071.5,2689818.0,700297.5,17440635.5,16514278.0,...,100.0,4.0,1.0,0.0,100.0,0.0,0.0,0.0,697298.5,665783068.0
Max,999.0,6400.75,3586064.0,65870.0,11462832.0,4121357.0,3586146.0,936418.0,23259098.0,22011962.0,...,100.0,10.0,2.5,0.0,100.0,0.0,0.0,0.0,1720119.25,902969616.0
IQR,499.0,2525.5,1796551.0,32895.5,5742964.5,2063700.0,1797245.0,466858.5,11607173.5,10997729.0,...,9.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,681880.5,422709665.5
Lower fence,-498.5,-3701.25,-1796737.5,-32912.25,-5731860.25,-2071178.5,-1803294.5,-466848.75,-11577298.25,-10980044.5,...,77.5,-6.0,-1.5,0.0,97.5,0.0,0.0,0.0,-1007402.75,-390991095.75
Upper fence,1497.5,6400.75,5389466.5,98669.75,17239997.75,6183621.5,5385685.5,1400585.25,34851395.75,33010871.5,...,113.5,10.0,2.5,0.0,101.5,0.0,0.0,0.0,1720119.25,1299847566.25
Skew,0.000823,1.205814,-0.001633,0.000258,-0.008414,0.002242,-0.002659,0.007312,0.000119,-0.001265,...,-1.22817,1.315047,1.098748,0.0,-0.947267,0.0,0.0,0.0,1.205281,-0.003579
Num_Outliers,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Percent_Outliers,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,...,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%

## Estratégia de Limpeza 6 - Transformação de Dados

Ter a soma dos volumes de dados de upload e download para cada aplicativo como um total pode ser necessário para análises futuras

Então vamos concatenar as colunas

In [58]:
df_limpo['Social Media Data Volume (Bytes)'] = df_limpo['Social Media UL (Bytes)'] + df_limpo['Social Media DL (Bytes)']

In [59]:
df_limpo['Google Data Volume (Bytes)'] = df_limpo['Google UL (Bytes)'] + df_limpo['Google DL (Bytes)']

In [60]:
df_limpo['Email Data Volume (Bytes)'] = df_limpo['Email UL (Bytes)'] + df_limpo['Email DL (Bytes)']

In [61]:
df_limpo['Youtube Data Volume (Bytes)'] = df_limpo['Youtube UL (Bytes)'] + df_limpo['Youtube DL (Bytes)']

In [62]:
df_limpo['Netflix Data Volume (Bytes)'] = df_limpo['Netflix UL (Bytes)'] + df_limpo['Netflix DL (Bytes)']

In [63]:
df_limpo['Gaming Data Volume (Bytes)'] = df_limpo['Gaming UL (Bytes)'] + df_limpo['Gaming DL (Bytes)']

In [64]:
df_limpo['Other Data Volume (Bytes)'] = df_limpo['Other UL (Bytes)'] + df_limpo['Other DL (Bytes)']

In [65]:
df_limpo['Total Data Volume (Bytes)'] = df_limpo['Total UL (Bytes)'] + df_limpo['Total DL (Bytes)']

In [66]:
df_limpo.shape

(146887, 54)

### <font color='blue'>Salvando os dados após a limpeza</font>

In [67]:
df_limpo.to_csv('Novo_dataset.csv')

### <font color='blue'>FIM</font>